workflows:
  android-release:
    name: Android Release (APK + AAB)
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      groups:
        - codemagic
      vars:
        GODOT_VERSION: "4.5.1"
      android_signing:
        - "1"
    scripts:
      - name: Install dependencies
        script: |
          set -e
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk unzip wget
          java -version
      - name: Install Godot and export templates
        script: |
          set -e
          echo "Using GODOT_VERSION=$GODOT_VERSION"
          cd /tmp
          
          wget -q https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          unzip Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          chmod +x Godot_v${GODOT_VERSION}-stable_linux.x86_64
          sudo mv Godot_v${GODOT_VERSION}-stable_linux.x86_64 /usr/local/bin/godot
          
          which godot
          godot --version
          
          mkdir -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          wget -q https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          cp -r templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable/
      - name: Prepare Android signing (from CodeMagic identities)
        script: |
          set -e
          cd $CM_BUILD_DIR
          
          # Диагностический вывод переменных CodeMagic
          echo "=== CodeMagic signing variables diagnostics ==="
          echo "CM_KEYSTORE_PATH=$CM_KEYSTORE_PATH"
          [ -n "$CM_KEYSTORE_PASSWORD" ] && echo "CM_KEYSTORE_PASSWORD is SET" || echo "CM_KEYSTORE_PASSWORD is EMPTY"
          [ -n "$CM_KEY_ALIAS" ] && echo "CM_KEY_ALIAS is SET" || echo "CM_KEY_ALIAS is EMPTY"
          [ -z "$CM_KEY_PASSWORD" ] && echo "CM_KEY_PASSWORD is EMPTY" || echo "CM_KEY_PASSWORD is SET"
          ls -la "$CM_KEYSTORE_PATH" || true
          echo "================================================"
          
          # Проверим, что CodeMagic реально дал переменные
          test -f "$CM_KEYSTORE_PATH" || (echo "CM_KEYSTORE_PATH not found" && exit 1)
          test -n "$CM_KEYSTORE_PASSWORD" || (echo "CM_KEYSTORE_PASSWORD empty" && exit 1)
          test -n "$CM_KEY_ALIAS" || (echo "CM_KEY_ALIAS empty" && exit 1)
          
          # Fallback для CM_KEY_PASSWORD: если пустой, используем CM_KEYSTORE_PASSWORD
          KEY_PASSWORD_EFFECTIVE="$CM_KEY_PASSWORD"
          if [ -z "$KEY_PASSWORD_EFFECTIVE" ]; then
            echo "CM_KEY_PASSWORD is empty, falling back to CM_KEYSTORE_PASSWORD"
            KEY_PASSWORD_EFFECTIVE="$CM_KEYSTORE_PASSWORD"
          fi
          
          # Кладем keystore в проект (НЕ коммитим)
          mkdir -p android_signing
          cp "$CM_KEYSTORE_PATH" android_signing/release.jks
          
          # Создаём keystore.properties для Gradle (НЕ коммитим)
          cat > keystore.properties <<EOF
          storeFile=android_signing/release.jks
          storePassword=$CM_KEYSTORE_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          keyPassword=$KEY_PASSWORD_EFFECTIVE
          EOF
          
          echo "Prepared keystore + keystore.properties"
          ls -la android_signing
      - name: Fix Gradle wrapper permissions
        script: |
          set -e
          cd $CM_BUILD_DIR
          ls -la android/build/gradlew || true
          chmod +x android/build/gradlew
          ls -la android/build/gradlew
      - name: Export APK
        script: |
          set -e
          mkdir -p build
          godot --headless --path . \
            --export-release "Android APK" build/ChickenAdventure-release.apk
      - name: Export AAB
        script: |
          set -e
          godot --headless --path . \
            --export-release "Android AAB" build/ChickenAdventure-release.aab
    artifacts:
      - build/*.apk
      - build/*.aab
